import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Counter } from '../features/Counter/Counter'
import styles from '../styles/Home.module.css'
import ListProducts from './products'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <ListProducts/>
      </main>
    </div>
  )
}

export default Home
